# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6c4ce9892178ced8cc4aa0cc860a7fd60b6558f1f5c767cc19f13127b02cb5f64c17a1279dd8c265cfe3f36b1222e435edc969129d482e78ab6ec45ef00cd3

test:
  secret_key_base: db9f04224af485b23893477090ddf04b283e98a57594a52d8bda1426c917067913e8a837a64b1c7a6af56dae14a27104d8cbedab4f2af5bdb54714d475cc87d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
